kind: Service
apiVersion: v1
metadata:
  name: myproject
  labels:
    app: myproject
spec:
  type: ClusterIP
  selector:
    app: myproject
  ports:
    - name: tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: myproject
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myproject
  template:
    metadata:
      labels:
        app: myproject
        version: v1
    spec:
      containers:
      - name: myproject
        image: myproject
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080

server:
  port: 8080

db:
  source: jdbc
  connection:
    url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1
    username: sa
    password: ""
